language: rust

rust:
  - stable
  - beta
  - nightly

branches:
  only:
    - master

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

os:
  - linux

script:
  - |
      cd wayland-sys &&
      travis-cargo test -- --features "dlopen egl client" &&
      cd ../scanner &&
      travis-cargo test &&
      cd ../wayland-client &&
      travis-cargo test -- --features "dlopen egl" &&
      cd ..
      travis-cargo --only stable doc -- -p wayland-sys --no-deps &&
      travis-cargo --only stable doc -- -p wayland-scanner --no-deps &&
      travis-cargo --only stable doc -- -p wayland-client --no-deps &&

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
