[package]
name = "wayland-client"
version = "0.3.0"
documentation = "http://vberger.github.io/wayland-client-rs/wayland_client/"
repository = "https://github.com/vberger/wayland-client-rs"
authors = ["Victor Berger <victor.berger@m4x.org>"]
license = "MIT"
description = "Bindings to the standard C implementation of the wayland protocol."

[dependencies]
dlib = "0.1"
libc = "0.1"

[features]
dlopen = ["dlib/dlopen"]
